[package]
name = "r-network"
version = "0.1.0"
edition = "2021"

[dependencies]
r-crypto = { workspace = true }
r-protocol = { workspace = true }

libp2p = { version = "0.54", features = [
    "tokio",
    "gossipsub",
    "kad",
    "identify",
    "ping",
    "noise",
    "tcp",
    "quic",
    "yamux",
    "request-response",
    "relay",
    "dcutr",
    "dns",
    "autonat",
    "macros",
    "cbor",
] }
tokio = { workspace = true, features = ["net", "io-util", "sync", "rt-multi-thread", "macros"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1.6"
futures = "0.3"
thiserror = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
tracing = "0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
