[package]
name = "r-network"
version = "0.1.0"
edition = "2021"

[dependencies]
r-protocol = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1.6"
futures = "0.3"
thiserror = { workspace = true }


[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
r-crypto = { workspace = true }
